export default function DisclaimerPage() {
  return (
    <main className="legal-wrap">
      <div className="wrap legal-content">
        <h1 className="section-title size-l">Disclaimer</h1>
        <p className="legal-updated">Last updated: September 2026</p>

        <h2>Not medical or professional advice</h2>
        <p>
          Cherri provides general wellness and nutrition information
          based on typical dietary data and established formulas. Nothing
          on Cherri, including calorie targets, macro breakdowns, body
          composition estimates, nutrition scores, or meal plans,
          constitutes medical, dietetic, or professional health advice.
        </p>

        <h2>Body Estimator tool</h2>
        <p>
          The Body Estimator provides an estimated BMI and body fat
          percentage using established formulas based on height, weight,
          age, and gender. These are general estimates and do not account
          for individual factors like muscle mass, bone density,
          pregnancy, or specific health conditions. They are not a
          substitute for a clinical body composition assessment.
        </p>

        <h2>Meal Planner and Snap a Plate</h2>
        <p>
          Meal plans generated by Cherri are based on general calorie and
          budget targets and do not account for allergies, medical
          dietary restrictions, or interactions with medication unless
          explicitly provided by you. Always double check ingredients
          against any allergies or restrictions you have. AI-identified
          meals from photos are estimates and should be reviewed for
          accuracy before logging.
        </p>

        <h2>Consult a professional</h2>
        <p>
          Before starting any new diet, exercise routine, or significant
          change to your eating habits, especially if you are pregnant,
          nursing, managing a chronic condition, or taking medication,
          please consult a qualified healthcare provider or registered
          dietitian.
        </p>

        <h2>No guarantee of results</h2>
        <p>
          Individual results from using Cherri will vary. We do not
          guarantee any specific health outcome, weight change, or
          nutritional result from using our tools.
        </p>

        <h2>Contact us</h2>
        <p>
          Questions about this disclaimer? Reach us at{' '}
          <a href="mailto:hello@cherri.com">hello@cherri.com</a>.
        </p>
      </div>
    </main>
  );
}